version: '3.8'
services:
    frontend:
        build:
            context: .
            dockerfile: dockerfile.dev
        ports:
            - '3000:3000'
        volumes:
            - ./src:/app/src
            - ./env:/app/env
            - ./node_modules:/app/node_modules
        command: ['npm', 'run', 'start']
        environment:
            - CHOKIDAR_USEPOLLING=true
        tty: true