FROM node:lts-alpine

# set working directory
WORKDIR /app



# install app dependencies
COPY package.json ./
COPY yarn.lock ./
RUN npm install

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# add app
COPY . ./

EXPOSE 3000
# start app
CMD ["npm", "run" , "start"]